package pk.models;
// Generated Mar 18, 2021 3:55:37 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Promotion generated by hbm2java
 */
@Entity
@Table(name="PROMOTION"
    ,schema="MINE"
)
public class Promotion  implements java.io.Serializable {


     private int idprom;
     private Produit produit;
     private Date dateDebut;
     private Date dateFin;
     private Byte taux;

    public Promotion() {
    }

	
    public Promotion(int idprom) {
        this.idprom = idprom;
    }
    public Promotion(int idprom, Produit produit, Date dateDebut, Date dateFin, Byte taux) {
       this.idprom = idprom;
       this.produit = produit;
       this.dateDebut = dateDebut;
       this.dateFin = dateFin;
       this.taux = taux;
    }
   
     @Id 

    
    @Column(name="IDPROM", unique=true, nullable=false, precision=8, scale=0)
    public int getIdprom() {
        return this.idprom;
    }
    
    public void setIdprom(int idprom) {
        this.idprom = idprom;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDP")
    public Produit getProduit() {
        return this.produit;
    }
    
    public void setProduit(Produit produit) {
        this.produit = produit;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_DEBUT", length=7)
    public Date getDateDebut() {
        return this.dateDebut;
    }
    
    public void setDateDebut(Date dateDebut) {
        this.dateDebut = dateDebut;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_FIN", length=7)
    public Date getDateFin() {
        return this.dateFin;
    }
    
    public void setDateFin(Date dateFin) {
        this.dateFin = dateFin;
    }

    
    @Column(name="TAUX", precision=2, scale=0)
    public Byte getTaux() {
        return this.taux;
    }
    
    public void setTaux(Byte taux) {
        this.taux = taux;
    }




}


