package pk.models;
// Generated Mar 18, 2021 3:55:37 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Publicite generated by hbm2java
 */
@Entity
@Table(name="PUBLICITE"
    ,schema="MINE"
)
public class Publicite  implements java.io.Serializable {


     private long idpub;
     private String image;

    public Publicite() {
    }

	
    public Publicite(long idpub) {
        this.idpub = idpub;
    }
    public Publicite(long idpub, String image) {
       this.idpub = idpub;
       this.image = image;
    }
   
     @Id 

    
    @Column(name="IDPUB", unique=true, nullable=false, precision=10, scale=0)
    public long getIdpub() {
        return this.idpub;
    }
    
    public void setIdpub(long idpub) {
        this.idpub = idpub;
    }

    
    @Column(name="IMAGE", length=250)
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }




}


