package pk.models;
// Generated Mar 18, 2021 3:55:37 PM by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Wishlist generated by hbm2java
 */
@Entity
@Table(name="WISHLIST"
    ,schema="MINE"
)
@SequenceGenerator(name = "client_ws",sequenceName = "client_ws")
public class Wishlist  implements java.io.Serializable {


     private long idw;
     private Client client;
     private String libelle;
     private List<Produit> produits = new ArrayList<Produit>(0);

    public Wishlist() {
    }

	
    public Wishlist(long idw) {
        this.idw = idw;
    }
    public Wishlist(long idw, Client client, String libelle, List<Produit> produits) {
       this.idw = idw;
       this.client = client;
       this.libelle = libelle;
       this.produits = produits;
    }
   
     @Id 
  @GeneratedValue(generator = "client_ws",strategy = GenerationType.SEQUENCE)    
    
    @Column(name="IDW", unique=true, nullable=false, precision=10, scale=0)
    public long getIdw() {
        return this.idw;
    }
    
    public void setIdw(long idw) {
        this.idw = idw;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDC")
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }

    
    @Column(name="LIBELLE", length=30)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="ITEMWISHLIST", schema="MINE", joinColumns = { 
        @JoinColumn(name="IDW", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="IDP", nullable=false, updatable=false) })
    public List<Produit> getProduits() {
        return this.produits;
    }
    
    public void setProduits(List<Produit> produits) {
        this.produits = produits;
    }




}


